name: learn-github-actions
on: [push]
env:
  buildConfiguration: "Release"
  wwwrootDir: "Tailspin.SpaceGame.Web/wwwroot"
  dotnetSdkVersion: "5.x
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Setup node
      - uses: actions/setup-dotnet@v1
        name: Setup dotnet
        with:
          dotnet-version: ${{ env.dotnetSdkVersion }}


