name: learn-github-actions
on: [push]
jobs:
  build-and-pack-project:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: "Release"
      WWW_ROOT_DIR: "Tailspin.SpaceGame.Web/wwwroot"
      DOTNET_SDK_VERSION: "5.x"

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Npm install
        run: npm install

      - name: "Compile Sass assets"
        run: ./node_modules/.bin/node-sass ${{ env.WWW_ROOT_DIR }} --output ${{ env.WWW_ROOT_DIR }}

      - name: Run gulp tasks
        run: gulp

      - name: Restore
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test

      - name: Create the package
        run: dotnet publish -c ${{ env.BUILD_CONFIG }} -o ${{ github.WORKSPACE }}/release

      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ${{ github.WORKSPACE }}/release

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: artifact
          path: ${{ github.WORKSPACE }}/release

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy web app
        id: deploywebapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: kp-app-n6rbwr4r46wsy-action
          package: artifact

      - name: az cli logout
        run: az logout
